[package]
name = "meta-traits"
version = "0.1.0"
authors = ["jdeepee <josh@junto.foundation>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_derive = "1.0"
hdk = "=0.0.47-alpha1"
holochain_wasm_utils = "=0.0.47-alpha1"
holochain_json_derive = "0.0"
hdk_proc_macros = "=0.0.47-alpha1"
activitystreams = "0.7.0-alpha.3"
mockall = "0.7.2"